
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BusinessLogic.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Invintation
{

    public int InvintationID { get; set; }

    public int CurrentUserID { get; set; }

    public int RequestedUserID { get; set; }

    public bool Accepted { get; set; }

}

}
