
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BusinessLogic.Models
{

using System;
    using System.Collections.Generic;
    
public partial class UserImage
{

    public UserImage()
    {

        this.UserImageComments = new HashSet<UserImageComment>();

    }


    public int ImageID { get; set; }

    public int UserID { get; set; }

    public string Comment { get; set; }

    public bool Deleted { get; set; }

    public string FileName { get; set; }

    public System.DateTime Date { get; set; }



    public virtual User User { get; set; }

    public virtual ICollection<UserImageComment> UserImageComments { get; set; }

}

}
